server:
  port: 8888

spring:
  application:
    name: course-schedule
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/course_schedule?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: csHikariCP
      max-lifetime: 12000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  mvc:
    static-path-pattern: /static/**
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java/**

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.neusoft.course.schedule.schedule.entity




#showSql
logging:
  level:
    com.neusoft.course.schedule: DEBUG


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql